[platformio]
default_envs = mega2-sim

[env]
monitor_port = COM11
monitor_speed = 115200
upload_port = COM11

[env:mega2-sim]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

build_flags =
    -DMEGA2_DEBUG=1
    -DMEGA2_SIM_MODE=1

monitor_filters = send_on_enter, printable

[env:mega2-hw]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

build_flags =
    -DMEGA2_DEBUG=1
    -DMEGA2_SIM_MODE=0

monitor_filters = send_on_enter, printable

; Backwards compatibility: keep old env name "mega2" (SIM by default)
[env:mega2]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

build_flags =
    -DMEGA2_DEBUG=1
    -DMEGA2_SIM_MODE=1

monitor_filters = send_on_enter, printable
